from enum import StrEnum


class DomainErrorCodeEnum(StrEnum):
    # ------------------------- General -------------------------
    GENERAL = "DOMAIN_GENERAL"
    INVALID_VALUE = "DOMAIN_INVALID_VALUE"
    REQUIRED_FIELD = "DOMAIN_REQUIRED_FIELD"
    MAX_LENGTH_EXCEEDED = "DOMAIN_MAX_LENGTH_EXCEEDED"
    RULE_VIOLATION = "DOMAIN_RULE_VIOLATION"
    UNIQUE_CONSTRAINT_VIOLATION = "DOMAIN_UNIQUE_CONSTRAINT_VIOLATION"
    NOT_FOUND = "DOMAIN_NOT_FOUND"
    OPERATION_NOT_ALLOWED = "DOMAIN_OPERATION_NOT_ALLOWED"
    PASSWORD_ERROR = "DOMAIN_PASSWORD_ERROR"

    # ------------------------- JWT Related -------------------------
    JWT_ERROR = "DOMAIN_JWT_ERROR"
    JWT_EXPIRED = "DOMAIN_JWT_EXPIRED"
    JWT_REVOKED = "DOMAIN_JWT_REVOKED"
    JWT_INVALID = "DOMAIN_JWT_INVALID"
    JWT_NOT_YET_VALID = "DOMAIN_JWT_NOT_YET_VALID"
