from enum import StrEnum


class DomainErrorCodeEnum(StrEnum):
    GENERAL = "DOMAIN_GENERAL"
    INVALID_VALUE = "DOMAIN_INVALID_VALUE"
    REQUIRED_FIELD = "DOMAIN_REQUIRED_FIELD"
    MAX_LENGTH_EXCEEDED = "DOMAIN_MAX_LENGTH_EXCEEDED"
    RULE_VIOLATION = "DOMAIN_RULE_VIOLATION"
    UNIQUE_CONSTRAINT_VIOLATION = "DOMAIN_UNIQUE_CONSTRAINT_VIOLATION"
    NOT_FOUND = "DOMAIN_NOT_FOUND"
    OPERATION_NOT_ALLOWED = "DOMAIN_OPERATION_NOT_ALLOWED"
    PASSWORD_ERROR = "DOMAIN_PASSWORD_ERROR"
