[project]
name = "authenticator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]==0.119.0",
    "pwdlib[argon2]==0.2.1",
    "pydantic==2.12.3",
    "pydantic-settings==2.11.0",
    "pyjwt==2.10.1",
]
