from enum import StrEnum


class DeliveryErrorCodeEnum(StrEnum):
    GENERAL = "DELIVERY_GENERAL"
    REQUEST_PARSING_FAILED = "DELIVERY_REQUEST_PARSING_FAILED"
    RESPONSE_SERIALIZATION_FAILED = "DELIVERY_RESPONSE_SERIALIZATION_FAILED"
